services:
  chrome:
    image: zenika/alpine-chrome:latest
    container_name: shadowave-chrome
    command:
      [
        chromium-browser,
        '--headless',
        '--remote-debugging-address=0.0.0.0',
        '--remote-debugging-port=9222',
        '--disable-extensions',
        '--disable-gpu',
      ]
    ports:
      - '9222:9222'
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - chrome_network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 512M
          cpus: '1'

  api:
    container_name: shadowave-api
    environment:
      SHADOWAVE_PORT: 3001
      SHADOWAVE_BROWSER_URL: http://chrome:9222
    build:
      context: .
      dockerfile: /apps/api/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - chrome
    networks:
      - chrome_network

networks:
  chrome_network:
    driver: bridge